// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJIIcIfXXmKeeGPbJuEdLnuGcJWAuNM0',
    appId: '1:197684801942:web:a786a4431a9e396e10edb7',
    messagingSenderId: '197684801942',
    projectId: 'getrooms-36a65',
    authDomain: 'getrooms-36a65.firebaseapp.com',
    storageBucket: 'getrooms-36a65.firebasestorage.app',
    measurementId: 'G-QS50732FGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoT4JP5z7VliD47KJYL5iibezZduKbihQ',
    appId: '1:197684801942:android:81665ab81f0842e110edb7',
    messagingSenderId: '197684801942',
    projectId: 'getrooms-36a65',
    storageBucket: 'getrooms-36a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-X3UZLg9zz8OorWcyswpSEQ7UdY4xTI',
    appId: '1:197684801942:ios:26ecf4fa4022b7a310edb7',
    messagingSenderId: '197684801942',
    projectId: 'getrooms-36a65',
    storageBucket: 'getrooms-36a65.firebasestorage.app',
    iosBundleId: 'com.example.getroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJIIcIfXXmKeeGPbJuEdLnuGcJWAuNM0',
    appId: '1:197684801942:web:d75351fcdd4c857110edb7',
    messagingSenderId: '197684801942',
    projectId: 'getrooms-36a65',
    authDomain: 'getrooms-36a65.firebaseapp.com',
    storageBucket: 'getrooms-36a65.firebasestorage.app',
    measurementId: 'G-EVV8KYZ8XT',
  );
}
